# Machine learning to make prediction for Zulaiha

In [1]:
import sklearn as sk
import pandas as pd

In [3]:
pd.read_csv("Co2_Emissions_by_Sectors.csv")

,Industry_Type,Region,Country,Year,Co2_Emissions_MetricTons,Energy_Consumption_TWh,Automobile_Co2_Emissions_MetricTons,Industrial_Co2_Emissions_MetricTons,Agriculture_Co2_Emissions_MetricTons,Domestic_Co2_Emissions_MetricTons,Population_Millions,GDP_Billion_USD,Urbanization_Percentage,Renewable_Energy_Percentage,Industrial_Growth_Percentage,Transport_Growth_Percentage
0,Construction,North America,Brazil,2010,89.13,90.14,98.37,118.36,31.41,0.77,941.06,13096.32,52.79,7.78,11.17,2.93
1,Mining,Europe,Germany,2006,224.81,931.70,10.81,66.73,39.45,0.21,1421.94,24337.71,50.18,31.52,13.34,9.30
2,Manufacturing,South America,South Africa,2017,179.72,255.14,55.36,111.67,1.25,4.97,522.75,24523.17,65.22,5.91,-9.88,4.77
3,Construction,Europe,India,2018,23.28,887.29,78.99,123.60,46.81,13.77,1304.60,12616.18,23.69,7.52,-0.64,8.21
4,Construction,Africa,China,2013,124.54,923.03,65.93,52.32,35.67,13.91,1437.68,4476.00,94.64,8.54,5.98,0.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17681,Manufacturing,Asia,South Africa,2020,177.73,132.27,32.44,90.00,49.83,10.25,849.67,22734.11,62.10,24.19,-8.38,5.79
17682,Energy,Africa,Germany,2009,11.89,615.87,71.90,122.81,3.05,1.50,581.74,14655.12,21.78,29.93,11.33,9.92
17683,Mining,South America,Canada,2017,47.94,564.24,32.63,47.54,47.54,15.02,898.74,16334.18,87.90,55.32,11.33,4.51
17684,Energy,Europe,USA,2012,211.15,826.48,36.02,122.83,19.24,15.82,28.58,20961.68,84.39,51.29,12.82,4.89
17685,Manufacturing,Oceania,China,2004,200.73,970.36,55.00,36.85,27.19,5.70,591.45,11039.64,36.16,69.48,13.29,1.04